apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
spec:
  containers:
    - name: traffic-generator
      image: lironefitoussi/traffic-generator:1.0.0
      args:
        - "color-api-svc/api"
        - "0.5"