apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/local1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage

---

apiVersion: v1
kind: Pod
metadata:
  name: local-volume-pod
  labels:
    app: local-volume-pod
spec:
  containers:
    - name: local-volume
      image: busybox:1.36.1
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      volumeMounts:
        - name: local-volume
          mountPath: /mnt/local
  volumes:
    - name:  local-volume
      persistentVolumeClaim:
        claimName: local-volume-claim

---

apiVersion: v1
kind: Pod
metadata:
  name: local-volume-pod2
  labels:
    app: local-volume-pod2
spec:
  containers:
    - name: local-volume
      image: busybox:1.36.1
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      volumeMounts:
        - name: local-volume
          mountPath: /mnt/local2
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: local-volume-claim