services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.db-key-value
    environment:
      - MONGODB_HOST=db
      - PORT=3000
    networks:
      - key-value-net
    depends_on:
      - db
      # - cache
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules
    # volumes:
    #   - type: bind
    #     source: ./backend/src
    #     target: /app/src
      # - './backend/src:/app/src:ro'
  db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204    
    ports:
      - "27017:27017"
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=root
    #   - MONGODB_INITDB_ROOT_PASSWORD=root_password
    env_file:
      - .env.db-root-creds
      - .env.db-key-value
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
      # - './db-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
      - type: volume
        source: mongodb-data
        target: /data/db    
    networks:
      - key-value-net
volumes:
  mongodb-data:
networks:
  key-value-net: