apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
  # annotations:
  #   description: "This is a simple nginx pod for demonstration purposes."
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27.0
    ports:
    - containerPort: 80